_core:
  default_config_hash: g-e4KOW89y24oWx5Nj4ja9LT1dlo8HCd6f3YG_9eqrE
features:
  comment_user_picture: 1
  comment_user_verification: 1
  favicon: 1
  logo: true
  name: true
  node_user_picture: 1
  slogan: true
logo:
  use_default: 0
  path: 'public://logo.png'
favicon:
  use_default: 0
  path: 'public://favicon.png'
  mimetype: image/png
sm_icon_facebook: 'https://www.facebook.com/flashwebcenter'
sm_icon_twitter: 'https://x.com/flashwebcenter'
sm_icon_pinterest: 'https://www.pinterest.com/alaahaddad'
sm_icon_linkedin: 'https://www.linkedin.com/company/flash-web-center'
sm_icon_instagram: 'https://www.instagram.com/flashwebcenter'
sm_icon_youtube: 'https://www.youtube.com/user/flashwebcenter'
sm_icon_snapchat: 'https://www.drupal.org/u/flashwebcenter'
sm_icon_reddit: 'https://www.drupal.org/u/flashwebcenter'
sm_icon_tiktok: 'https://www.drupal.org/u/flashwebcenter'
sm_icon_whatsapp: 'https://www.drupal.org/u/flashwebcenter'
sm_icon_threads: 'https://www.drupal.org/u/flashwebcenter'
sm_icon_drupal: 'https://www.drupal.org/u/flashwebcenter'
sm_icon_mastodon: 'https://www.drupal.org/u/flashwebcenter'
sm_icon_rss: rss.xml
sm_icon_email: '/#email'
footer_copyright: ''
sm_show_icons: 0
sm_icon_size: sm-icons-small
footer_link: ''
footer_link_label: ''
footer_link_text: ''
count_main: 1
site_global_width: sw-1600
site_global_breakpoints: sb-992
site_global_regions_gap: '16'
site_global_font_size: '16'
site_menu_breakpoints: mn-992
header_login_links: Login
predefined_current_theme: soft_and_subtle_hues|solo-magnolia-afternoon
theme_category: soft_and_subtle_hues
color_coded_system_tabs: 1
site_breadcrumb_scroll: 1
count_top: 0
count_bottom: 0
count_footer: 0
enable_custom_node_width_message: ''
enable_custom_widths: 0
site_width_article: sw-1600
site_width_page: sw-1600
site_width_task: sw-1600
site_node_date_format: solo_date_l
site_import_google_font: ''
site_css_injector: ''
site_css_dynamic: ''
site_js_dynamic: ''
site_login_page_on: 0
site_flip_header_menu: 0
site_opacity_onscroll_on: 0
site_inline_items_on: 0
site_reading_mode_content_type: {  }
site_load_w3css_on: 0
site_font_google_local_on: 0
site_font_awesome_on: '0'
site_font_google_global_on: solo-lato
site_font_google_heading_on: ''
site_font_google_special_on: ''
classes_page_wrapper: ''
opacity_page_wrapper: 0
settings_page_wrapper___r_bg: ''
settings_page_wrapper___r_tx: ''
settings_page_wrapper___r_h1: ''
settings_page_wrapper___r_lk: ''
settings_page_wrapper___r_lk_h: ''
settings_page_wrapper___r_br: '#643a3a'
settings_page_wrapper___r_bg_fr: ''
settings_page_wrapper___r_tx_lk: ''
settings_page_wrapper___r_tx_lk_h: ''
settings_page_wrapper___r_bg_lk: ''
settings_page_wrapper___r_bg_lk_h: ''
settings_page_wrapper___r_tx_bt: ''
settings_page_wrapper___r_tx_bt_h: ''
settings_page_wrapper___r_bg_bt: ''
settings_page_wrapper___r_bg_bt_h: ''
classes_popup_login_block: ''
header_popup_login: 0
settings_popup_login_block___r_bg: ''
settings_popup_login_block___r_tx: ''
settings_popup_login_block___r_h1: ''
settings_popup_login_block___r_lk: ''
settings_popup_login_block___r_lk_h: ''
settings_popup_login_block___r_br: ''
settings_popup_login_block___r_bg_fr: ''
settings_popup_login_block___r_tx_lk: ''
settings_popup_login_block___r_tx_lk_h: ''
settings_popup_login_block___r_bg_lk: ''
settings_popup_login_block___r_bg_lk_h: ''
settings_popup_login_block___r_tx_bt: ''
settings_popup_login_block___r_tx_bt_h: ''
settings_popup_login_block___r_bg_bt: ''
settings_popup_login_block___r_bg_bt_h: ''
classes_fixed_search_block: ''
settings_fixed_search_block___r_bg: ''
settings_fixed_search_block___r_tx: ''
settings_fixed_search_block___r_h1: ''
settings_fixed_search_block___r_lk: ''
settings_fixed_search_block___r_lk_h: ''
settings_fixed_search_block___r_br: ''
settings_fixed_search_block___r_bg_fr: ''
settings_fixed_search_block___r_tx_lk: ''
settings_fixed_search_block___r_tx_lk_h: ''
settings_fixed_search_block___r_bg_lk: ''
settings_fixed_search_block___r_bg_lk_h: ''
settings_fixed_search_block___r_tx_bt: ''
settings_fixed_search_block___r_tx_bt_h: ''
settings_fixed_search_block___r_bg_bt: ''
settings_fixed_search_block___r_bg_bt_h: ''
classes_header: ''
header_logo_image_alt: ''
header_sitename_center_default: 0
header_sitename_center: 0
header_sitename_center_small: 0
header_change_icons: 0
site_name_font_size_s: ''
site_name_font_size_l: ''
site_name_google_font: ''
site_name_animate_on: ''
settings_header___r_bg: ''
settings_header___r_tx: ''
settings_header___r_h1: ''
settings_header___r_lk: ''
settings_header___r_lk_h: ''
settings_header___r_br: ''
settings_header___r_bg_fr: ''
settings_header___r_tx_lk: ''
settings_header___r_tx_lk_h: ''
settings_header___r_bg_lk: ''
settings_header___r_bg_lk_h: ''
settings_header___r_tx_bt: ''
settings_header___r_tx_bt_h: ''
settings_header___r_bg_bt: ''
settings_header___r_bg_bt_h: ''
classes_primary_menu: ''
primary_menu_on_hover: 0
primary_menu_border: 0
primary_menu_align_center: 0
primary_menu_branding: 0
primary_menu_justify_content: 0
primary_menu_expand_left: 0
primary_menu_keyboard: 0
primary_menu_megamenu: 0
primary_menu_megamenu_layout: m-1-1
primary_menu_submenu_header: 0
settings_primary_menu___r_bg: ''
settings_primary_menu___r_tx: ''
settings_primary_menu___r_h1: ''
settings_primary_menu___r_lk: ''
settings_primary_menu___r_lk_h: ''
settings_primary_menu___r_br: ''
settings_primary_menu___r_bg_fr: ''
settings_primary_menu___r_tx_lk: ''
settings_primary_menu___r_tx_lk_h: ''
settings_primary_menu___r_bg_lk: ''
settings_primary_menu___r_bg_lk_h: ''
settings_primary_menu___r_tx_bt: ''
settings_primary_menu___r_tx_bt_h: ''
settings_primary_menu___r_bg_bt: ''
settings_primary_menu___r_bg_bt_h: ''
classes_system_messages: ''
system_messages_disable_dark: 0
settings_system_messages___r_bg: ''
settings_system_messages___r_tx: ''
settings_system_messages___r_h1: ''
settings_system_messages___r_lk: ''
settings_system_messages___r_lk_h: ''
settings_system_messages___r_br: ''
settings_system_messages___r_bg_fr: ''
settings_system_messages___r_tx_lk: ''
settings_system_messages___r_tx_lk_h: ''
settings_system_messages___r_bg_lk: ''
settings_system_messages___r_bg_lk_h: ''
settings_system_messages___r_tx_bt: ''
settings_system_messages___r_tx_bt_h: ''
settings_system_messages___r_bg_bt: ''
settings_system_messages___r_bg_bt_h: ''
classes_page_title: ''
site_pagetitle_font_size_s: ''
site_pagetitle_font_size_l: ''
site_pagetitle_google_font: ''
site_pagetitle_animate_on: ''
site_pagetitle_center: 0
settings_page_title___r_bg: ''
settings_page_title___r_tx: ''
settings_page_title___r_h1: ''
settings_page_title___r_lk: ''
settings_page_title___r_lk_h: ''
settings_page_title___r_br: ''
settings_page_title___r_bg_fr: ''
settings_page_title___r_tx_lk: ''
settings_page_title___r_tx_lk_h: ''
settings_page_title___r_bg_lk: ''
settings_page_title___r_bg_lk_h: ''
settings_page_title___r_tx_bt: ''
settings_page_title___r_tx_bt_h: ''
settings_page_title___r_bg_bt: ''
settings_page_title___r_bg_bt_h: ''
classes_breadcrumb: ''
site_breadcrumb_pagetitle_off: 0
settings_breadcrumb___r_bg: ''
settings_breadcrumb___r_tx: ''
settings_breadcrumb___r_h1: ''
settings_breadcrumb___r_lk: ''
settings_breadcrumb___r_lk_h: ''
settings_breadcrumb___r_br: ''
settings_breadcrumb___r_bg_fr: ''
settings_breadcrumb___r_tx_lk: ''
settings_breadcrumb___r_tx_lk_h: ''
settings_breadcrumb___r_bg_lk: ''
settings_breadcrumb___r_bg_lk_h: ''
settings_breadcrumb___r_tx_bt: ''
settings_breadcrumb___r_tx_bt_h: ''
settings_breadcrumb___r_bg_bt: ''
settings_breadcrumb___r_bg_bt_h: ''
main_2col: solo-col-2-1
main_3col: solo-col-1-2-1
site_regions_main_rounded: ''
site_mobile_layout_order: left_main_right
site_regions_main_border: 0
classes_main_container: ''
settings_main_container___r_bg: ''
settings_main_container___r_tx: ''
settings_main_container___r_h1: ''
settings_main_container___r_lk: ''
settings_main_container___r_lk_h: ''
settings_main_container___r_br: ''
settings_main_container___r_bg_fr: ''
settings_main_container___r_tx_lk: ''
settings_main_container___r_tx_lk_h: ''
settings_main_container___r_bg_lk: ''
settings_main_container___r_bg_lk_h: ''
settings_main_container___r_tx_bt: ''
settings_main_container___r_tx_bt_h: ''
settings_main_container___r_bg_bt: ''
settings_main_container___r_bg_bt_h: ''
classes_content: ''
settings_content___r_bg: ''
settings_content___r_tx: ''
settings_content___r_h1: ''
settings_content___r_lk: ''
settings_content___r_lk_h: ''
settings_content___r_br: ''
settings_content___r_bg_fr: ''
settings_content___r_tx_lk: ''
settings_content___r_tx_lk_h: ''
settings_content___r_bg_lk: ''
settings_content___r_bg_lk_h: ''
settings_content___r_tx_bt: ''
settings_content___r_tx_bt_h: ''
settings_content___r_bg_bt: ''
settings_content___r_bg_bt_h: ''
classes_sidebar_second: ''
settings_sidebar_second___r_bg: ''
settings_sidebar_second___r_tx: ''
settings_sidebar_second___r_h1: ''
settings_sidebar_second___r_lk: ''
settings_sidebar_second___r_lk_h: ''
settings_sidebar_second___r_br: ''
settings_sidebar_second___r_bg_fr: ''
settings_sidebar_second___r_tx_lk: ''
settings_sidebar_second___r_tx_lk_h: ''
settings_sidebar_second___r_bg_lk: ''
settings_sidebar_second___r_bg_lk_h: ''
settings_sidebar_second___r_tx_bt: ''
settings_sidebar_second___r_tx_bt_h: ''
settings_sidebar_second___r_bg_bt: ''
settings_sidebar_second___r_bg_bt_h: ''
classes_footer_menu: ''
settings_footer_menu___r_bg: ''
settings_footer_menu___r_tx: ''
settings_footer_menu___r_h1: ''
settings_footer_menu___r_lk: ''
settings_footer_menu___r_lk_h: ''
settings_footer_menu___r_br: ''
settings_footer_menu___r_bg_fr: ''
settings_footer_menu___r_tx_lk: ''
settings_footer_menu___r_tx_lk_h: ''
settings_footer_menu___r_bg_lk: ''
settings_footer_menu___r_bg_lk_h: ''
settings_footer_menu___r_tx_bt: ''
settings_footer_menu___r_tx_bt_h: ''
settings_footer_menu___r_bg_bt: ''
settings_footer_menu___r_bg_bt_h: ''
sm_icon_colors: ''
sm_icon_telegram: ''
classes_credit_copyright: ''
settings_credit_copyright___r_bg: ''
settings_credit_copyright___r_tx: ''
settings_credit_copyright___r_h1: ''
settings_credit_copyright___r_lk: ''
settings_credit_copyright___r_lk_h: ''
settings_credit_copyright___r_br: ''
settings_credit_copyright___r_bg_fr: ''
settings_credit_copyright___r_tx_lk: ''
settings_credit_copyright___r_tx_lk_h: ''
settings_credit_copyright___r_bg_lk: ''
settings_credit_copyright___r_bg_lk_h: ''
settings_credit_copyright___r_tx_bt: ''
settings_credit_copyright___r_tx_bt_h: ''
settings_credit_copyright___r_bg_bt: ''
settings_credit_copyright___r_bg_bt_h: ''
